=== 1907931256/zxite/SciteNet/ScintillaNET.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Scintilla">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="globals" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="value" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="name" type="xs:string" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="style-classes" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="style-class" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
									<xs:attribute name="fore" type="xs:string" />
									<xs:attribute name="back" type="xs:string" />
									<xs:attribute name="size" type="xs:string" />
									<xs:attribute name="font" type="xs:string" />
									<xs:attribute name="bold">
										<xs:simpleType>
											<xs:restriction base="xs:NMTOKEN">
												<xs:enumeration value="true" />
												<xs:enumeration value="false" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="italics">
										<xs:simpleType>
											<xs:restriction base="xs:NMTOKEN">
												<xs:enumeration value="true" />
												<xs:enumeration value="false" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="inherit-style" type="xs:string" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="keyword-classes" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="keyword-class" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="name" type="xs:string" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="language" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="lexer" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="file-extensions" type="xs:string" minOccurs="0" />
							<xs:element name="use-keywords" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="keyword" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="key" type="xs:string" use="required" />
												<xs:attribute name="class" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="use-styles" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="style" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
												<xs:attribute name="key" type="xs:string" use="required" />
												<xs:attribute name="class" type="xs:string" use="required" />
												<xs:attribute name="fore" type="xs:string" />
												<xs:attribute name="back" type="xs:string" />
												<xs:attribute name="size" type="xs:string" />
												<xs:attribute name="font" type="xs:string" />
												<xs:attribute name="bold">
													<xs:simpleType>
														<xs:restriction base="xs:NMTOKEN">
															<xs:enumeration value="true" />
															<xs:enumeration value="false" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="italics">
													<xs:simpleType>
														<xs:restriction base="xs:NMTOKEN">
															<xs:enumeration value="true" />
															<xs:enumeration value="false" />
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== 1907931256/zxite/SciteNet/ScintillaNET.xml
<?xml version="1.0" encoding="utf-8" ?>
	<Scintilla xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ScintillaNET.xsd">
	<globals>
		<value name="comment-font">Lucida Sans Unicode</value>
		<value name="strange-color2"></value>
		<value name="strange-color3"/>
		<value name="keyword-color">blue</value>
		<value name="comment-color">red</value>
		<value name="strange-color">0x013310</value>
		<!-- values are first matched back into the global set. -->
		<value name="code-color">strange-color</value>
	</globals>
	<style-classes>
		<!-- All styles inherit the default style. -->
		<style-class name="default" key="32" fore="0x000000" back="0xFFFFFF" size="10" font="Lucida Console" />
		<!-- the bold style adds bold=true to the parent -->
		<style-class name="bold" bold="true" fore="comment-color"/>
		<style-class name="important" inherit-style="bold" italics="true" />
		<style-class name="comment" inherit-style="bold" fore="comment-color" />
		<style-class name="kword" inherit-style="bold" fore="keyword-color" />
	</style-classes>
	<keyword-classes>
		<keyword-class name="javascript">
				abstract boolean break byte case catch char class 
				const continue debugger default delete do double else enum export extends 
				final finally float for function goto if implements import in instanceof 
				int interface long native new package private protected public 
				return short static super switch synchronized this throw throws 
				transient try typeof var void volatile while with
			</keyword-class>
	</keyword-classes>
	<language name="javascript">
		<!-- Settings for coloring and handling Javascript -->
		<lexer name="cpp" key="3" />
		<file-extensions>js js7</file-extensions>
		<use-keywords>
			<keyword key="0" class="javascript" />
		</use-keywords>
		<use-styles>
			<style name="DEFAULT" key="0" class="default" fore="0xFFFF00" />
			<style name="COMMENT" key="1" class="comment" />
			<style name="COMMENTLINE" key="2" class="comment" fore="0x0000ff" />
			<style name="COMMENTDOC" key="3" class="comment" fore="0x00FFFF" />
			<style name="NUMBER" key="4" class="default" fore="0x00FF00" />
			<style name="WORD" key="5" class="kword" />
			<style name="STRING" key="6" class="default" />
			<style name="CHARACTER" key="7" class="default" />
			<style name="UUID" key="8" class="default" />
			<style name="PREPROCESSOR" key="9" class="default" />
			<style name="OPERATOR" key="10" class="default" />
			<style name="IDENTIFIER" key="11" class="default" />
			<style name="STRINGEOL" key="12" class="default" />
			<style name="VERBATIM" key="13" class="default" />
			<style name="REGEX" key="14" class="important" />
			<style name="COMMENTLINEDOC" key="15" class="default" />
			<style name="WORD2" key="16" class="kword" />
			<style name="COMMENTDOCKEYWORD" key="17" class="default" />
			<style name="COMMENTDOCKEYWORDERROR" key="18" class="default" />
		</use-styles>
	</language>
	<language name="hypertext">
		<!-- *** Sample Only. ***-->
		<!-- Settings for coloring and handling Hypertext -->
		<lexer name="html" key="0" />
		<file-extensions>html htm</file-extensions>
		<use-keywords>
			<keyword key="0" class="hypertext" />
			<keyword key="1" class="javascript" />
			<keyword key="2" class="vbscript" />
			<keyword key="3" class="python" />
			<keyword key="4" class="php" />
			<keyword key="5" class="sgml-dtd" />
		</use-keywords>
		<use-styles>
			<style name="DEFAULT" key="0" class="default" />
			<!-- ommited for berevity :) -->
		</use-styles>
	</language>
</Scintilla>
